name: rest_api_server
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.2

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  path: ^1.9.0
  # dart pub add mysql1
  # flutter pub add mysql1
  mysql1: ^0.20.0
  mongo_dart: ^0.10.5
  sqlite3: ^2.7.6



dev_dependencies:
  http: ^1.1.0
  lints: ^5.0.0
  test: ^1.24.0
